#%RAML 1.0
title: uw-exp-api

/uw-user:
  post: 
   body:
    application/json:
      example:
        {
          "emailid":"",
          "firstname": "",
          "lastname": ""
          
        }
   responses:
    200:
      body:
        application/json:
          example:
            {
              "status": "success",
              "sfid": "",
              "trnansactionId":""
            }
/uw-subscription:
  post: 
   body:
    application/json:
      example:
        {
          "emailid":"",
          "firstname": "",
          "lastname": ""
          
        }
   responses:
    200:
      body:
        application/json:
          example:
            {
              "status": "success",
              "sfid": "",
              "trnansactionId":""
            }